import {createActionGroup, emptyProps, props} from '@ngrx/store';

import {
  BootstrapResponse,
  BulkUpdateTicketsRequest,
  CreateActivityHookRequest,
  CreateProjectRequest,
  CreateSavedTicketFilterRequest,
  CreateTicketCommentRequest,
  CreateTicketRequest,
  CreateTicketTypeRequest,
  CreateUserRequest,
  LoginRequest,
  LoginResponse,
  Project,
  PublicUser,
  SavedTicketFilter,
  SaveWorkflowRequest,
  Ticket,
  TicketDetailResponse,
  TicketRevisionDetail,
  TicketRevisionSummary,
  UpdateActivityHookRequest,
  UpdateProjectRequest,
  UpdateSavedTicketFilterRequest,
  UpdateTicketTypeRequest,
  UpdateUserRequest
} from '../core/api.models';
import {
  MyTicketsFilters,
  AdminPage,
  RouteWorkspaceState,
  ThemeMode,
  TicketDialogSave,
  TicketDialogState,
  TicketFilters,
  UpdateTicketWithTransition,
  WorkflowStatusPatch,
  WorkflowTransitionPatch,
  WorkspaceTab
} from './queue.models';

export const QueueActions = createActionGroup({
  source: 'Queue',
  events: {
    'App Started': props<{ token: string | null; passwordChangeRequired: boolean }>(),
    'Login Requested': props<{ request: LoginRequest }>(),
    'Login Succeeded': props<LoginResponse>(),
    'Login Failed': props<{ error: string }>(),
    'Logout Requested': emptyProps(),
    'Logout Completed': emptyProps(),
    'Theme Initialized': props<{ theme: ThemeMode }>(),
    'Theme Toggled': emptyProps(),

    'Bootstrap Requested': emptyProps(),
    'Bootstrap Succeeded': props<{ data: BootstrapResponse }>(),
    'Bootstrap Failed': props<{ error: string }>(),

    'Route State Changed': props<{ state: RouteWorkspaceState }>(),
    'Project Selected': props<{ projectId: string }>(),
    'Tab Selected': props<{ tab: WorkspaceTab }>(),
    'Admin Page Selected': props<{ page: AdminPage }>(),
    'Ticket Detail Opened': props<{ ticketId: string }>(),
    'Ticket Detail Load Requested': props<{ ticketId: string }>(),
    'Ticket Detail Load Succeeded': props<{ detail: TicketDetailResponse }>(),
    'Ticket Detail Load Failed': props<{ error: string }>(),
    'Older Revisions Requested': props<{ ticketId: string; beforeVersion: number }>(),
    'Older Revisions Loaded': props<{ revisions: TicketRevisionSummary[]; nextBeforeVersion: number | null }>(),
    'Revision Open Requested': props<{ ticketId: string; version: number }>(),
    'Revision Opened': props<{ detail: TicketRevisionDetail }>(),
    'Revision Closed': emptyProps(),
    'Revision Restore Requested': props<{ ticketId: string; version: number; expectedVersion: number }>(),
    'Detail Closed': emptyProps(),
    'Filters Changed': props<{ filters: Partial<TicketFilters> }>(),
    'My Tickets Filters Changed': props<{ filters: Partial<MyTicketsFilters> }>(),
    'Saved Ticket Filter Applied': props<{ filter: SavedTicketFilter }>(),

    'Ticket Dialog Opened': props<TicketDialogState>(),
    'Ticket Dialog Closed': emptyProps(),
    'Ticket Dialog Saved': props<TicketDialogSave>(),
    'Ticket Create Requested': props<{ request: CreateTicketRequest }>(),
    'Ticket Update Requested': props<UpdateTicketWithTransition>(),
    'Ticket Update Version Conflict': props<{ save: UpdateTicketWithTransition; currentVersion: number }>(),
    'Ticket Conflict Dismissed': emptyProps(),
    'Ticket Conflict Reload Requested': props<{ ticketId: string }>(),
    'Ticket Transition Requested': props<{ ticket: Ticket; toStatusId: string }>(),
    'Ticket Delete Requested': props<{ ticketId: string; expectedVersion: number }>(),
    'Ticket Restore Requested': props<{ ticketId: string; expectedVersion: number }>(),
    'Ticket Commitment Requested': props<{ ticketId: string; committed: boolean; expectedVersion: number }>(),
    'Tickets Bulk Update Requested': props<{ request: BulkUpdateTicketsRequest }>(),
    'Comment Create Requested': props<{ ticketId: string; request: CreateTicketCommentRequest }>(),

    'Project Create Requested': props<{ request: CreateProjectRequest }>(),
    'Project Created': props<{ project: Project }>(),
    'Project Create Failed': props<{ error: string }>(),
    'Project Wizard Opened': emptyProps(),
    'Project Wizard Closed': emptyProps(),
    'Project Update Requested': props<{ projectId: string; request: UpdateProjectRequest }>(),
    'Project Delete Requested': props<{ projectId: string }>(),
    'Project Deleted': props<{ projectId: string }>(),
    'User Create Requested': props<{ request: CreateUserRequest; generateTemporaryPassword: boolean }>(),
    'User Update Requested': props<{ userId: string; request: UpdateUserRequest }>(),
    'User Temporary Password Requested': props<{ user: PublicUser }>(),
    'User Temporary Password Generated': emptyProps(),
    'Ticket Type Create Requested': props<{ request: CreateTicketTypeRequest }>(),
    'Ticket Type Update Requested': props<{ typeId: string; request: UpdateTicketTypeRequest }>(),
    'Ticket Type Delete Requested': props<{ typeId: string }>(),
    'Workflow Save Requested': props<{ projectId: string; request: SaveWorkflowRequest }>(),
    'Saved Ticket Filter Create Requested': props<{ request: CreateSavedTicketFilterRequest }>(),
    'Saved Ticket Filter Update Requested': props<{ filterId: string; request: UpdateSavedTicketFilterRequest }>(),
    'Saved Ticket Filter Delete Requested': props<{ filterId: string }>(),
    'Activity Hook Create Requested': props<{ request: CreateActivityHookRequest }>(),
    'Activity Hook Update Requested': props<{ hookId: string; request: UpdateActivityHookRequest }>(),
    'Activity Hook Delete Requested': props<{ hookId: string }>(),

    'Mutation Succeeded': props<{ message?: string; focusTicketId?: string }>(),
    'Mutation Failed': props<{ error: string }>(),

    'Workflow Draft Reset': emptyProps(),
    'Workflow Status Added': emptyProps(),
    'Workflow Status Patched': props<WorkflowStatusPatch>(),
    'Workflow Status Removed': props<{ index: number }>(),
    'Workflow Status Moved': props<{ index: number; direction: -1 | 1 }>(),
    'Workflow Transition Added': emptyProps(),
    'Workflow Transition Patched': props<WorkflowTransitionPatch>(),
    'Workflow Transition Removed': props<{ index: number }>(),

    'Toast Shown': props<{ message: string }>(),
    'Toast Cleared': emptyProps()
  }
});
